/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  env: {
    // Auth0
    AUTH0_SECRET: process.env.AUTH0_SECRET,
    AUTH0_BASE_URL: process.env.AUTH0_BASE_URL,
    AUTH0_ISSUER_BASE_URL: process.env.AUTH0_ISSUER_BASE_URL,
    AUTH0_CLIENT_ID: process.env.AUTH0_CLIENT_ID,
    AUTH0_CLIENT_SECRET: process.env.AUTH0_CLIENT_SECRET,
    
    // AI Models (Using Groq with Llama 3.3 70B)
    GROQ_API_KEY: process.env.GROQ_API_KEY,
    
    // Google OAuth
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    GOOGLE_REDIRECT_URI: process.env.GOOGLE_REDIRECT_URI,
    
    // AWS DynamoDB
    AWS_REGION: process.env.AWS_REGION,
    AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
    
    // DynamoDB Tables
    DYNAMODB_AGENTS_TABLE: process.env.DYNAMODB_AGENTS_TABLE,
    DYNAMODB_EXECUTIONS_TABLE: process.env.DYNAMODB_EXECUTIONS_TABLE,
    DYNAMODB_MEMORY_TABLE: process.env.DYNAMODB_MEMORY_TABLE,
    DYNAMODB_KNOWLEDGE_BASES_TABLE: process.env.DYNAMODB_KNOWLEDGE_BASES_TABLE,
    DYNAMODB_VECTORS_TABLE: process.env.DYNAMODB_VECTORS_TABLE,
    DYNAMODB_RULES_TABLE: process.env.DYNAMODB_RULES_TABLE,
    DYNAMODB_TOOLS_TABLE: process.env.DYNAMODB_TOOLS_TABLE,
    DYNAMODB_CONNECTIONS_TABLE: process.env.DYNAMODB_CONNECTIONS_TABLE,
    DYNAMODB_ANALYTICS_TABLE: process.env.DYNAMODB_ANALYTICS_TABLE,
    
    // AWS S3
    AWS_S3_BUCKET: process.env.AWS_S3_BUCKET,
    AWS_LAMBDA_FUNCTION: process.env.AWS_LAMBDA_FUNCTION,
    
    // Slack OAuth
    SLACK_CLIENT_ID: process.env.SLACK_CLIENT_ID,
    SLACK_CLIENT_SECRET: process.env.SLACK_CLIENT_SECRET,
    SLACK_REDIRECT_URI: process.env.SLACK_REDIRECT_URI,
  },
};

export default nextConfig;
